version: 2

defaults: &defaults
  working_directory: ~/project/vue
  docker:
    - image: vuejs/ci
jobs:
  build-and-deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --network-timeout 600000
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - project/vue
      - run:
          name: Configuration
          command: |
            git config user.email "rholang"
            git config user.name "rholang"
      - add_ssh_keys:
          fingerprints:
            - 'ad:1d:24:40:b5:4b:8e:e4:4c:6b:f7:b5:6a:49:6a:ce'
      - run:
          name: Deploy to GH
          command: yarn deploy

workflows:
  build-and-test:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: source
